application:
  host: 0.0.0.0 #used for docker image networking: ENV APP_ENVIRONMENT production
database:
  require_ssl: true
email_client:
  base_url: "https://someurl.com"
  sender_email: "someone@gmail.com"
